name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install ninja
      run: sudo apt install ninja-build
    - name: Checkout llvm
      uses: actions/checkout@v2
      with:
        repository: llvm/llvm-project
        ref: llvmorg-9.0.1
        path: llvm-project
    - name: Checkout clang-export-types
      uses: actions/checkout@v2
      with:
        path: llvm-project/clang-tools-extra/clang-export-types
    - name: Add clang-export-types to CMake
      run: |
        pwd
        ls -lah
        echo 'add_subdirectory(clang-export-types)' >> llvm-project/clang-tools-extra/CMakeLists.txt
    - name: Setup build folder
      run: |
        pwd
        ls -lah
        mkdir build
    - name: Build clang-tools-extra
      run: |
        pwd
        ls -lah
        cd build
        cmake -G Ninja ../llvm-project/llvm -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"
        ninja clang-export-types
